apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-app
  labels:
    app: postgres
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP  # Internal only
