apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: my-app
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted as read-write by a single node
  resources:
    requests:
      storage: 5Gi # Request 5 GB of storage
  # storageClassName: "standard" # Optional: if you have a specific StorageClass (e.g., AWS EBS, GCE Persistent Disk)
