apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-app
type: Opaque
data:
  # Base64 encoded values for sensitive data
  # Use 'echo -n "your_db_password" | base64' to generate these
  DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  API_KEY: <BASE64_ENCODED_API_KEY> # Example for backend
