apiVersion: v1
kind: Secret
metadata:
  name: my-app-secrets
  namespace: my-app
type: Opaque
data:

  DB_PASSWORD: <BASE64_ENCODED_DB_PASSWORD>
  API_KEY: <BASE64_ENCODED_API_KEY> # Example for backend
