version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80" # Map host port 3000 to container port 80 (Nginx)
    depends_on:
      - backend
    environment:
      - REACT_APP_API_BASE_URL=http://backend:8000 # For React to know backend URL

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: photos_db
      MYSQL_HOST: db # This matches the service name for the database
      SECRET_KEY: "your-super-secret-key" # Keep this secret!

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password # Strong password for root
      MYSQL_DATABASE: photos_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306" # Optional: expose DB port for local access (e.g., DBeaver)
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql # Initialize database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data: # Define a named volume for persistent database data
